version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    environment:
      - cluster.name=elasticsearch
      - node.name=elasticsearch-{{.Task.Slot}}
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "node.max_local_storage_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./mounts/elasticsearch_data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./mounts/logstash/pipeline/:/usr/share/logstash/pipeline
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME_FILE=/run/secrets/elasticsearch_username
      - ELASTICSEARCH_PASSWORD_FILE=/run/secrets/elasticsearch_password
    ports:
      - 5000:5000
    secrets:
      - elasticsearch_username
      - elasticsearch_password
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana.example.com
      - ELASTICSEARCH_USERNAME_FILE=/run/secrets/elasticsearch_username
      - ELASTICSEARCH_PASSWORD_FILE=/run/secrets/elasticsearch_password
    secrets:
      - elasticsearch_username
      - elasticsearch_password
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:

secrets:
  elasticsearch_username:
    external: true
  elasticsearch_password:
    external: true

